<?php

namespace Insertion\Controller\Backend;

use Doctrine\ORM\ORMException;
use Insertion\Services\AttributeService;
use Oforge\Engine\Modules\AdminBackend\Core\Abstracts\SecureBackendController;
use Oforge\Engine\Modules\Core\Annotation\Endpoint\EndpointClass;
use Oforge\Engine\Modules\Core\Exceptions\ServiceNotFoundException;
use Slim\Http\Request;
use Slim\Http\Response;

/**
 * Class FrontendHelpdeskController
 *
 * @package Insertion\Controller\Backend
 * @EndpointClass(path="/backend/insertion/attribute", name="backend_attribute", assetScope="Backend")
 */
class BackendAttributeController extends SecureBackendController {
    /**
     * @param Request $request
     * @param Response $response
     *
     * @throws ServiceNotFoundException
     */
    public function indexAction(Request $request, Response $response) {
        /** @var AttributeService $attributeService */
        $attributeService = Oforge()->Services()->get('insertion.attribute');
    }

    public function initPermissions() {
        parent::initPermissions(); // TODO: Change the autogenerated stub
    }
}