<?php

namespace Helpdesk\Controller\Frontend;

use FrontendUserManagement\Abstracts\SecureFrontendController;
use Oforge\Engine\Modules\Core\Annotation\Endpoint\EndpointAction;
use Oforge\Engine\Modules\Core\Annotation\Endpoint\EndpointClass;
use Slim\Http\Request;
use Slim\Http\Response;

/**
 * Class FrontendHelpdeskController
 *
 * @package Helpdesk\Controller\Frontend
 * @EndpointClass(path="/account/support", name="frontend_account_support", assetScope="Frontend")
 */
class FrontendHelpdeskController extends SecureFrontendController {

    /**
     * @param Request $request
     * @param Response $response
     * @EndpointAction()
     */
    public function indexAction(Request $request, Response $response) {
        // TODO
    }

    public function initPermissions() {
        parent::initPermissions(); // TODO: Change the autogenerated stub
    }

}
