<?php
/**
 * Created by PhpStorm.
 * User: Alexander Wegner
 * Date: 16.01.2019
 * Time: 12:13
 */

namespace Oforge\Engine\Modules\CMS\ContentTypes;

use Oforge\Engine\Modules\CMS\Abstracts\AbstractContentType;

class Image extends AbstractContentType {
    public function load(int $id) {
        return parent::load($id); // TODO: Change the autogenerated stub
    }
    public function save(array $params) {
        parent::save($params); // TODO: Change the autogenerated stub
    }
}
