<?php

namespace Mailchimp;

use Oforge\Engine\Modules\Core\Abstracts\AbstractBootstrap;
use Mailchimp\Controller\Frontend\NewsletterSubscriptionController;
use Mailchimp\Services\MailchimpNewsletterService;

class Bootstrap extends AbstractBootstrap
{
    public function __construct()
    {
        $this->endpoints = [
            "/newsletter" => ["controller" => NewsletterSubscriptionController::class, "name" => "frontend_newsletter_subscription"],
        ];
        $this->services = [
            'mailchimp.newsletter' => MailchimpNewsletterService::class,
        ];
    }

    public function activate()
    {
        parent::activate(); // TODO: Change the autogenerated stub
    }

    public function deactivate()
    {
        parent::deactivate(); // TODO: Change the autogenerated stub
    }

    public function uninstall()
    {
        parent::uninstall(); // TODO: Change the autogenerated stub
    }
}