<?php


namespace Translation;


use Oforge\Engine\Modules\Core\Abstracts\AbstractBootstrap;
use Translation\Services\TranslationService;

/**
 * Class Bootstrap
 *
 * @package Oforge\Engine\Plugins\Translation
 */
class Bootstrap extends AbstractBootstrap
{
    public function __construct()
    {
        $this->endpoints = [
        ];

        $this->models = [
        ];

        $this->services = [
            'translation' => TranslationService::class
        ];
    }

    public function install()
    {
        parent::install(); // TODO: Change the autogenerated stub
    }

    public function activate()
    {
        parent::activate(); // TODO: Change the autogenerated stub
    }

    public function deactivate()
    {
        parent::deactivate(); // TODO: Change the autogenerated stub
    }

    public function uninstall()
    {
        parent::uninstall(); // TODO: Change the autogenerated stub
    }
}
