<?php
/**
 * Created by PhpStorm.
 * User: Alexander Wegner
 * Date: 16.01.2019
 * Time: 12:13
 */

namespace Oforge\Engine\Modules\CMS\ContentTypes;

use Oforge\Engine\Modules\CMS\Abstracts\AbstractContentType;

class Image extends AbstractContentType {
    
    public function init() {
        setConfigurationValue("width", "100px");
        setConfigurationValue("height", "100px");
        setConfigurationValue("margin-top", "0");
        setConfigurationValue("margin-left", "0");
        setConfigurationValue("margin-bottom", "0");
        setConfigurationValue("margin-right", "0");
        setConfigurationValue("padding-top", "0");
        setConfigurationValue("padding-left", "0");
        setConfigurationValue("padding-bottom", "0");
        setConfigurationValue("padding-right", "0");
        setConfigurationValue("border-style", "1");
        setConfigurationValue("border-size", "solid");
        setConfigurationValue("border-color", "#000");
    }
    
    public function load(int $id) {
        return parent::load($id); // TODO: Change the autogenerated stub
    }
    
    public function save(array $params) {
        parent::save($params); // TODO: Change the autogenerated stub
    }
}
